migrateup:
	migrate -path dblocal/migration -database "postgres://root:password@localhost:5432/db?sslmode=disable" -verbose up
migratedown:
	migrate -path dblocal/migration -database "postgres://root:password@localhost:5432/db?sslmode=disable" -verbose down